steps:
- name: 'gcr.io/cel-analysis/bazel:3.0.0'
  entrypoint: bazel
  args: ['test', '--test_output=errors', '...']
  id: bazel-test
  waitFor: ['-']
timeout: 1h
options:
  machineType: 'N1_HIGHCPU_8'
