steps:
- name: 'gcr.io/cel-analysis/cel-cpp/ubuntu_floor@sha256:41392c9ad2347476495089401004f2a3e2e0f5b3a0be905a8601ae7899811ccb'
  args:
  - '--output_base=/bazel' # This is mandatory to avoid steps accidently sharing data.
  - 'test'
  - '...'
  - '--enable_bzlmod'
  - '--copt=-Wno-deprecated-declarations'
  - '--compilation_mode=fastbuild'
  - '--test_output=errors'
  - '--show_timestamps'
  - '--test_tag_filters=-benchmark,-notap'
  - '--jobs=HOST_CPUS*.5'
  - '--local_ram_resources=HOST_RAM*.4'
  - '--remote_cache=https://storage.googleapis.com/cel-cpp-remote-cache'
  - '--google_default_credentials'
  id: gcc-10
  waitFor: ['-']
- name: 'gcr.io/cel-analysis/cel-cpp/ubuntu_floor@sha256:41392c9ad2347476495089401004f2a3e2e0f5b3a0be905a8601ae7899811ccb'
  env:
  - 'CC=clang-12'
  - 'CXX=clang++-12'
  args:
  - '--output_base=/bazel' # This is mandatory to avoid steps accidently sharing data.
  - 'test'
  - '...'
  - '--enable_bzlmod'
  - '--copt=-Wno-deprecated-declarations'
  - '--compilation_mode=fastbuild'
  - '--test_output=errors'
  - '--show_timestamps'
  - '--test_tag_filters=-benchmark,-notap'
  - '--jobs=HOST_CPUS*.5'
  - '--local_ram_resources=HOST_RAM*.4'
  - '--remote_cache=https://storage.googleapis.com/cel-cpp-remote-cache'
  - '--google_default_credentials'
  id: clang-12
  waitFor: ['-']
timeout: 1h
options:
  machineType: 'E2_HIGHCPU_32'
