package(default_visibility = ["//visibility:public"])

exports_files(
    [
        "test.cel",
        "subtraction_checked_expr.textproto",
    ],
)

filegroup(
    name = "resources",
    srcs = glob([
        "*.textproto",
    ]),
)
