name: Bazel Test (Post-Merge)

on:
  push:
    branches:
      - master

jobs:
  trigger-win-latest-test:
    # This prevents the workflow from running automatically when someone
    # pushes to their fork.
    if: github.repository == 'cel-expr/cel-cpp'
    uses: ./.github/workflows/windows_bazel_test.yml
  trigger-mac-latest-test:
    if: github.repository == 'cel-expr/cel-cpp'
    uses: ./.github/workflows/macos_bazel_test.yml
