name: Windows Bazel Test (Post-Merge)

on:
  push:
    branches:
      - master

jobs:
  trigger-test:
    # This prevents the workflow from running automatically when someone
    # pushes to their fork.
    if: github.repository == 'google/cel-cpp'
    uses: ./.github/workflows/windows_bazel_test.yml